# Generated by Django 3.2.3 on 2021-05-25 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_duration', models.CharField(max_length=100)),
                ('upload_song', models.FileField(upload_to='./songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('joinDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
