# Generated by Django 3.2.3 on 2021-05-25 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_songdetail_upload_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdetail',
            name='upload_song',
            field=models.FileField(upload_to='./songs/mp3/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'wma', 'amr'])]),
        ),
    ]
