# Generated by Django 3.2.3 on 2021-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_songdetail_upload_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdetail',
            name='song_duration',
            field=models.IntegerField(),
        ),
    ]
